name: Bug report
description: Report a problem with SimHub
title: "[Bug] "
labels: [bug]

body:
  - type: textarea
    id: bug_description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: e.g., SimHub crashes when opening Dash Studio
    validations:
      required: true

  - type: input
    id: simhub_version
    attributes:
      label: SimHub version
      description: Make sure to run the latest version before reporting a bug.
      placeholder: e.g., 9.3.2
    validations:
      required: true

  - type: checkboxes
    id: plugin_check
    attributes:
      label: Third-party plugins
      description: |
        Before reporting any freeze, performance, or crash issues, please disable all third-party plugins.  
        [See the troubleshooting guide](https://github.com/SHWotever/SimHub/wiki/SimHub-Troubleshootings#disabling-any-third-party-plugin)
      options:
        - label: I have disabled all third-party plugins.
          required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: Steps to reproduce
      description: Please describe step-by-step how to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen instead?
      placeholder: A clear and concise description of what you expected to happen.

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem. You can drag and drop images here.

  - type: textarea
    id: logs
    attributes:
      label: 📁 Log files
      description: |
        Attach complete log files below.  
        - From `C:\Program Files (x86)\SimHub\Logs`  
        - Include:
          - `simhub.txt` (current run)
          - `simhub.1.txt`, `simhub.2.txt`, etc.
        - You can **drag and drop** the files directly into this box.  

        ⚠️ Bug reports without full logs will not be processed.  
        Do **not** attach screenshots or excerpts — only full `.txt` log files.  

        [How to attach files](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files)
      placeholder: |
        ⬇️ Drag and drop your `.txt` log files here, or paste them if needed.
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
