//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimingClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public Car()
        {
            this.Session = new HashSet<Session>();
        }
    
        public string Code { get; set; }
        public string Class { get; set; }
        public string parent { get; set; }
        public string brand { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string bhp { get; set; }
        public string torque { get; set; }
        public string weight { get; set; }
        public string topspeed { get; set; }
        public string acceleration { get; set; }
        public string pwratio { get; set; }
        public byte[] BadgePng { get; set; }
        public byte[] PreviewPng { get; set; }
    
        public virtual ICollection<Session> Session { get; set; }
    }
}
