//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimingClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lap
    {
        public int SessionId { get; set; }
        public int LapNumber { get; set; }
        public System.TimeSpan LapTime { get; set; }
        public string Timings { get; set; }
    
        public virtual Session Session { get; set; }
    }
}
