//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimingClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public Session()
        {
            this.Lap = new HashSet<Lap>();
        }
    
        public int SessionId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.TimeSpan> SessionLength { get; set; }
        public Nullable<int> PlayerId { get; set; }
        public string Car { get; set; }
        public string Track { get; set; }
        public Nullable<System.TimeSpan> BestLap { get; set; }
    
        public virtual Car Car1 { get; set; }
        public virtual Player Player { get; set; }
        public virtual Track Track1 { get; set; }
        public virtual ICollection<Lap> Lap { get; set; }
    }
}
